### ISSUE TITLE
Issues with Roles

### ISSUE THREAD

**Issue by bluefeet** [tobyink/p5-moox-classattribute#3]
Hello,

So, 03role.t works, but it doesn't actually test what I think is the real-world use case - where the roles and classes are in separate .pm files.  If you move Foo, WithFoo, Bar, and WithBar into separate .pm files, replace them with the following in 03role.t:

```
use WithFoo;
use WithBar;
```

And it _booms_:

Can't locate object method "foo" via package "WithFoo" at 03role.t line 25.

If I adjust the use statements to look like this:

```
use Foo;
use WithFoo;
use Bar;
use WithBar;
```

Everything works.

**Comment by tobyink** [comment]
Moved to https://rt.cpan.org/Ticket/Display.html?id=94752
